version: '2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_dev
    user: "node"
    working_dir: /home/node/app
    environment:
      - "NODE_ENV=dev"
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3000"
    command: bash -c "npm install && npm run start:dev"